DATA_PATH = "/opt/airflow/dags/data/"
ADDRESSES_CSV = DATA_PATH + "addresses.csv"
DISTRICTS_XLSX = DATA_PATH + "districts.xlsx"
ONEMAP_API_URL = "https://developers.onemap.sg/commonapi/search"
URA_ACCESS_KEY = "480de617-6aee-4c71-a04a-3b6c3a9596b2"